package com.erlanggariansyah.mahasiswamanagementspringdynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Setter
@DynamoDBTable(tableName = "Mahasiswa")
public class Mahasiswa {
    private String id;
    private String nama;
    private String jurusan;
    private Integer ipk;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getNama() {
        return nama;
    }

    @DynamoDBAttribute
    public String getJurusan() {
        return jurusan;
    }

    @DynamoDBAttribute
    public Integer getIpk() {
        return ipk;
    }
}
